import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <nav className={styles.nav}>
          <ul className={styles.listContainer}>
            <li className={styles.listItem}>Home</li>
            <li className={styles.listItem}>About</li>
            <li className={styles.listItem}>Contact</li>
          </ul>
        </nav>
        <div className={styles.description}>
          <p>Hunting Coder</p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to Learn Javascript?</h3>
            <p>
              Javascript is the language used to design logic for the web page
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to Learn Javascript?</h3>
            <p>
              Javascript is the language used to design logic for the web page
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to Learn Javascript?</h3>
            <p>
              Javascript is the language used to design logic for the web page
            </p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to Learn Javascript?</h3>
            <p>
              Javascript is the language used to design logic for the web page
            </p>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
      </main>
    </>
  );
}
